[package]
name = "packet_derive"
version = "0.1.1"
edition = "2021"
description = "Derive implementation for packet_enum"

[lib]
proc-macro = true

[dependencies]
packet_util = "0.1.1"
quote = "1.0.37"
syn = "2.0.85"
